### ISSUE TITLE
OCID not working with TLS1.3

### ISSUE THREAD

**Issue by Red96Baron** [EsperoTech/yaade#126]
When setting the "site"-parameter of the OCID configuration to an URL that requires TLS 1.3 as a minimum version, saving OICD configuration won't work: `Error: Discovery failed: Failed to create SSL connection`.

Decreasing the minimum TLS version to 1.2 fixes this error, but increasing it afterwards leeds to an error durig Login via OICD:

```{"cause":null,"stackTrace":[{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"handleFailure","fileName":"ServerError.kt","lineNumber":36,"className":"com.espero.yaade.server.errors.ServerErrorKt","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"handleFailure","fileName":"RouteState.java","lineNumber":1290,"className":"io.vertx.ext.web.impl.RouteState","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"iterateNext","fileName":"RoutingContextImplBase.java","lineNumber":170,"className":"io.vertx.ext.web.impl.RoutingContextImplBase","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"next","fileName":"RoutingContextWrapper.java","lineNumber":200,"className":"io.vertx.ext.web.impl.RoutingContextWrapper","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"handleFailure","fileName":"RouterImpl.java","lineNumber":256,"className":"io.vertx.ext.web.impl.RouterImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"handleFailure","fileName":"RouteState.java","lineNumber":1290,"className":"io.vertx.ext.web.impl.RouteState","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"iterateNext","fileName":"RoutingContextImplBase.java","lineNumber":170,"className":"io.vertx.ext.web.impl.RoutingContextImplBase","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"next","fileName":"RoutingContextImpl.java","lineNumber":140,"className":"io.vertx.ext.web.impl.RoutingContextImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"doFail","fileName":"RoutingContextImpl.java","lineNumber":543,"className":"io.vertx.ext.web.impl.RoutingContextImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"fail","fileName":"RoutingContextImpl.java","lineNumber":192,"className":"io.vertx.ext.web.impl.RoutingContextImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"fail","fileName":"RoutingContextImpl.java","lineNumber":181,"className":"io.vertx.ext.web.impl.RoutingContextImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"lambda$null$2","fileName":"OAuth2AuthHandlerImpl.java","lineNumber":478,"className":"io.vertx.ext.web.handler.impl.OAuth2AuthHandlerImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"onFailure","fileName":"FutureImpl.java","lineNumber":153,"className":"io.vertx.core.impl.future.FutureImpl$3","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"emitFailure","fileName":"FutureBase.java","lineNumber":75,"className":"io.vertx.core.impl.future.FutureBase","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"tryFail","fileName":"FutureImpl.java","lineNumber":230,"className":"io.vertx.core.impl.future.FutureImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"onFailure","fileName":"Composition.java","lineNumber":66,"className":"io.vertx.core.impl.future.Composition$1","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"emitFailure","fileName":"FutureBase.java","lineNumber":75,"className":"io.vertx.core.impl.future.FutureBase","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"addListener","fileName":"FailedFuture.java","lineNumber":98,"className":"io.vertx.core.impl.future.FailedFuture","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"onFailure","fileName":"Composition.java","lineNumber":55,"className":"io.vertx.core.impl.future.Composition","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"emitFailure","fileName":"FutureBase.java","lineNumber":75,"className":"io.vertx.core.impl.future.FutureBase","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"tryFail","fileName":"FutureImpl.java","lineNumber":230,"className":"io.vertx.core.impl.future.FutureImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"onFailure","fileName":"Composition.java","lineNumber":66,"className":"io.vertx.core.impl.future.Composition$1","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"emitFailure","fileName":"FutureBase.java","lineNumber":75,"className":"io.vertx.core.impl.future.FutureBase","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"addListener","fileName":"FailedFuture.java","lineNumber":98,"className":"io.vertx.core.impl.future.FailedFuture","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"onFailure","fileName":"Composition.java","lineNumber":55,"className":"io.vertx.core.impl.future.Composition","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"emitFailure","fileName":"FutureBase.java","lineNumber":75,"className":"io.vertx.core.impl.future.FutureBase","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"tryFail","fileName":"FutureImpl.java","lineNumber":230,"className":"io.vertx.core.impl.future.FutureImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"onFailure","fileName":"Composition.java","lineNumber":66,"className":"io.vertx.core.impl.future.Composition$1","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"emitFailure","fileName":"FutureBase.java","lineNumber":75,"className":"io.vertx.core.impl.future.FutureBase","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"addListener","fileName":"FailedFuture.java","lineNumber":98,"className":"io.vertx.core.impl.future.FailedFuture","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"onFailure","fileName":"Composition.java","lineNumber":55,"className":"io.vertx.core.impl.future.Composition","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"emitFailure","fileName":"FutureBase.java","lineNumber":75,"className":"io.vertx.core.impl.future.FutureBase","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"tryFail","fileName":"FutureImpl.java","lineNumber":230,"className":"io.vertx.core.impl.future.FutureImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"tryFail","fileName":"PromiseImpl.java","lineNumber":23,"className":"io.vertx.core.impl.future.PromiseImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"lambda$doRequest$8","fileName":"HttpClientImpl.java","lineNumber":645,"className":"io.vertx.core.http.impl.HttpClientImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"lambda$getConnection$0","fileName":"Endpoint.java","lineNumber":52,"className":"io.vertx.core.net.impl.pool.Endpoint","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"handle","fileName":"SharedClientHttpStreamEndpoint.java","lineNumber":162,"className":"io.vertx.core.http.impl.SharedClientHttpStreamEndpoint$Request","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"handle","fileName":"SharedClientHttpStreamEndpoint.java","lineNumber":123,"className":"io.vertx.core.http.impl.SharedClientHttpStreamEndpoint$Request","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"emit","fileName":"EventLoopContext.java","lineNumber":56,"className":"io.vertx.core.impl.EventLoopContext","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"emit","fileName":"ContextImpl.java","lineNumber":274,"className":"io.vertx.core.impl.ContextImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"emit","fileName":"EventLoopContext.java","lineNumber":23,"className":"io.vertx.core.impl.EventLoopContext","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"run","fileName":"SimpleConnectionPool.java","lineNumber":382,"className":"io.vertx.core.net.impl.pool.SimpleConnectionPool$ConnectFailed$1","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"submit","fileName":"CombinerExecutor.java","lineNumber":50,"className":"io.vertx.core.net.impl.pool.CombinerExecutor","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"execute","fileName":"SimpleConnectionPool.java","lineNumber":245,"className":"io.vertx.core.net.impl.pool.SimpleConnectionPool","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"lambda$connect$2","fileName":"SimpleConnectionPool.java","lineNumber":259,"className":"io.vertx.core.net.impl.pool.SimpleConnectionPool","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"lambda$connect$2","fileName":"SharedClientHttpStreamEndpoint.java","lineNumber":104,"className":"io.vertx.core.http.impl.SharedClientHttpStreamEndpoint","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"onFailure","fileName":"FutureImpl.java","lineNumber":153,"className":"io.vertx.core.impl.future.FutureImpl$3","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"emitFailure","fileName":"FutureBase.java","lineNumber":75,"className":"io.vertx.core.impl.future.FutureBase","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"tryFail","fileName":"FutureImpl.java","lineNumber":230,"className":"io.vertx.core.impl.future.FutureImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"onFailure","fileName":"Composition.java","lineNumber":66,"className":"io.vertx.core.impl.future.Composition$1","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"emitFailure","fileName":"FutureBase.java","lineNumber":75,"className":"io.vertx.core.impl.future.FutureBase","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"addListener","fileName":"FailedFuture.java","lineNumber":98,"className":"io.vertx.core.impl.future.FailedFuture","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"onFailure","fileName":"Composition.java","lineNumber":55,"className":"io.vertx.core.impl.future.Composition","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"emitFailure","fileName":"FutureBase.java","lineNumber":75,"className":"io.vertx.core.impl.future.FutureBase","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"tryFail","fileName":"FutureImpl.java","lineNumber":230,"className":"io.vertx.core.impl.future.FutureImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"tryFail","fileName":"PromiseImpl.java","lineNumber":23,"className":"io.vertx.core.impl.future.PromiseImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"emit","fileName":"EventLoopContext.java","lineNumber":56,"className":"io.vertx.core.impl.EventLoopContext","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"emit","fileName":"ContextImpl.java","lineNumber":274,"className":"io.vertx.core.impl.ContextImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"emit","fileName":"EventLoopContext.java","lineNumber":23,"className":"io.vertx.core.impl.EventLoopContext","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"failed","fileName":"NetClientImpl.java","lineNumber":294,"className":"io.vertx.core.net.impl.NetClientImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"lambda$connectInternal$4","fileName":"NetClientImpl.java","lineNumber":262,"className":"io.vertx.core.net.impl.NetClientImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"notifyListener0","fileName":"DefaultPromise.java","lineNumber":578,"className":"io.netty.util.concurrent.DefaultPromise","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"notifyListenersNow","fileName":"DefaultPromise.java","lineNumber":552,"className":"io.netty.util.concurrent.DefaultPromise","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"notifyListeners","fileName":"DefaultPromise.java","lineNumber":491,"className":"io.netty.util.concurrent.DefaultPromise","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"setValue0","fileName":"DefaultPromise.java","lineNumber":616,"className":"io.netty.util.concurrent.DefaultPromise","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"setFailure0","fileName":"DefaultPromise.java","lineNumber":609,"className":"io.netty.util.concurrent.DefaultPromise","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"setFailure","fileName":"DefaultPromise.java","lineNumber":109,"className":"io.netty.util.concurrent.DefaultPromise","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"userEventTriggered","fileName":"ChannelProvider.java","lineNumber":131,"className":"io.vertx.core.net.impl.ChannelProvider$1","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"invokeUserEventTriggered","fileName":"AbstractChannelHandlerContext.java","lineNumber":346,"className":"io.netty.channel.AbstractChannelHandlerContext","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"invokeUserEventTriggered","fileName":"AbstractChannelHandlerContext.java","lineNumber":332,"className":"io.netty.channel.AbstractChannelHandlerContext","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"fireUserEventTriggered","fileName":"AbstractChannelHandlerContext.java","lineNumber":324,"className":"io.netty.channel.AbstractChannelHandlerContext","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"handleUnwrapThrowable","fileName":"SslHandler.java","lineNumber":1259,"className":"io.netty.handler.ssl.SslHandler","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"decodeJdkCompatible","fileName":"SslHandler.java","lineNumber":1240,"className":"io.netty.handler.ssl.SslHandler","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"decode","fileName":"SslHandler.java","lineNumber":1284,"className":"io.netty.handler.ssl.SslHandler","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"decodeRemovalReentryProtection","fileName":"ByteToMessageDecoder.java","lineNumber":510,"className":"io.netty.handler.codec.ByteToMessageDecoder","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"callDecode","fileName":"ByteToMessageDecoder.java","lineNumber":449,"className":"io.netty.handler.codec.ByteToMessageDecoder","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"channelRead","fileName":"ByteToMessageDecoder.java","lineNumber":279,"className":"io.netty.handler.codec.ByteToMessageDecoder","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"invokeChannelRead","fileName":"AbstractChannelHandlerContext.java","lineNumber":379,"className":"io.netty.channel.AbstractChannelHandlerContext","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"invokeChannelRead","fileName":"AbstractChannelHandlerContext.java","lineNumber":365,"className":"io.netty.channel.AbstractChannelHandlerContext","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"fireChannelRead","fileName":"AbstractChannelHandlerContext.java","lineNumber":357,"className":"io.netty.channel.AbstractChannelHandlerContext","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"channelRead","fileName":"DefaultChannelPipeline.java","lineNumber":1410,"className":"io.netty.channel.DefaultChannelPipeline$HeadContext","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"invokeChannelRead","fileName":"AbstractChannelHandlerContext.java","lineNumber":379,"className":"io.netty.channel.AbstractChannelHandlerContext","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"invokeChannelRead","fileName":"AbstractChannelHandlerContext.java","lineNumber":365,"className":"io.netty.channel.AbstractChannelHandlerContext","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"fireChannelRead","fileName":"DefaultChannelPipeline.java","lineNumber":919,"className":"io.netty.channel.DefaultChannelPipeline","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"read","fileName":"AbstractNioByteChannel.java","lineNumber":166,"className":"io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"processSelectedKey","fileName":"NioEventLoop.java","lineNumber":722,"className":"io.netty.channel.nio.NioEventLoop","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"processSelectedKeysOptimized","fileName":"NioEventLoop.java","lineNumber":658,"className":"io.netty.channel.nio.NioEventLoop","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"processSelectedKeys","fileName":"NioEventLoop.java","lineNumber":584,"className":"io.netty.channel.nio.NioEventLoop","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"run","fileName":"NioEventLoop.java","lineNumber":496,"className":"io.netty.channel.nio.NioEventLoop","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"run","fileName":"SingleThreadEventExecutor.java","lineNumber":995,"className":"io.netty.util.concurrent.SingleThreadEventExecutor$4","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"run","fileName":"ThreadExecutorMap.java","lineNumber":74,"className":"io.netty.util.internal.ThreadExecutorMap$2","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"run","fileName":"FastThreadLocalRunnable.java","lineNumber":30,"className":"io.netty.util.concurrent.FastThreadLocalRunnable","nativeMethod":false},{"classLoaderName":null,"moduleName":"java.base","moduleVersion":"11.0.21","methodName":"run","fileName":"Thread.java","lineNumber":829,"className":"java.lang.Thread","nativeMethod":false}],"code":500,"message":"Failed to create SSL connection","suppressed":[],"localizedMessage":"Failed to create SSL connection"} ```

**Comment by jonrosner** [comment]
Thank you for reporting this issue. It might be because the used vert.x version does not support TLS 1.3.

What OIDC provider are you using? Can you provide a minimal reproducible example?

**Comment by Red96Baron** [comment]
Thank you very much for for your quick reply. In my case I am using Authentik behind Traefik reverse proxy. Providing a minimal reproducible example would therefore include traefik, which probably won't be considered minimal anymore. Especially as it works perfectly with TLS 1.2.

Therefore, I think this is less about my individual setup, but more about whether it might be feasible to support TLS 1.3 (by upgrading  vert.x?).

If you nevertheless think it makes sense for me to provide a configuration for traefik and Authentik, I will of course be happy to do so.

**Comment by jonrosner** [comment]
Yes, it would make as I will need an example to test if it works after upgrading. So if you could provide a few instructions to set up your traefik and authentic I could test it.

**Comment by Red96Baron** [comment]
Ok, I've put together a docker compose for you. But first a few preliminary details:

All containers use a specific network:
`docker network create -d bridge --gateway 172.20.255.1 --subnet 172.20.255.0/24 --ip-range 172.20.255.128/25 proxy`

The compose-file contains the following variables, which either need to be replaced with your actual values within the compose-file, or set (for example in the portainer stack.env):
```
${POSTGRES_PW} (= password for postgres-user "postgres")

${SECRET_KEY_FOR_AUTHENTIK} (= a secret authentik requires)

${DEFAULT_URL} (= your-domain-with-certs.com)
${DEFAULT_DOCKER_PATH} (= local path in which the followning folder structure should exist)
```

The following folders and files are referenced:
```
${DEFAULT_DOCKER_PATH}/ssl/your.cert
${DEFAULT_DOCKER_PATH}/ssl/your.key

${DEFAULT_DOCKER_PATH}/traefik/
${DEFAULT_DOCKER_PATH}/traefik/config/
${DEFAULT_DOCKER_PATH}/traefik/config/traefik.yml
${DEFAULT_DOCKER_PATH}/traefik/config/dyn/
${DEFAULT_DOCKER_PATH}/traefik/config/dyn/dynamic_conf.yml

${DEFAULT_DOCKER_PATH}/postgres

${DEFAULT_DOCKER_PATH}/ssl/
${DEFAULT_DOCKER_PATH}/ssl/your.cert
${DEFAULT_DOCKER_PATH}/ssl/your.key

${DEFAULT_DOCKER_PATH}/yaade/
${DEFAULT_DOCKER_PATH}/yaade/data/
```

The content of the config files should be similar to:

${DEFAULT_DOCKER_PATH}/traefik/config/traefik.yml:
```
global:
  checkNewVersion: true
  sendAnonymousUsage: false  # true by default

# (Optional) Log information
# ---
log:
  level: ERROR  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: common  # common, json, logfmt
  filePath: /var/log/traefik/traefik.log

# (Optional) Accesslog
# ---
accesslog:
  # format: common  # common, json, logfmt
  filePath: /var/log/traefik/access.log  
  bufferingSize: 50

# (Optional) Enable API and Dashboard
# ---
api:
  dashboard: true  # true by default
  insecure: true  # Don't do this in production!

## Static configuration
serversTransport:
  insecureSkipVerify: true

experimental:
  http3: true

# Entry Points configuration
# ---
entryPoints:
  web:
    address: :80
    proxyProtocol:
      insecure: true
    # (Optional) Redirect to HTTPS
    # ---
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: :443
    proxyProtocol:
      insecure: true
    http3:
      advertisedPort: 443

# Configure your CertificateResolver here...
# ---

# (Optional) Overwrite Default Certificates
tls:
  stores:
    default:
      defaultCertificate:
        certFile: /ssl/your.cert
        keyFile: /ssl/your.key

providers:
  # Enable the file provider to define routers / middlewares / services in file
  file:
    directory: /etc/traefik/dyn
    watch: true
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false  # Default is true
    network: proxy
    defaultRule: "Host(`{{ .Name }}.${DEFAULT_URL}`)"
```

${DEFAULT_DOCKER_PATH}/traefik/config/dyn/dynamic_conf.yml
```
tls:
  options:
    default:
      minVersion: VersionTLS13 #here you can change the actual TLS-Version
      sniStrict: true
      alpnProtocols:
        - http/1.1
        - h2
        - acme-tls/1
        - dot
```

And finally the actual compose-file:
```
version: '3.7'
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    hostname: traefik.${DEFAULT_URL}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      proxy:
        ipv4_address: 172.20.255.2
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 443
        published: 443
        mode: host
        protocol: udp
      - target: 8080
        published: 8080
        mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DEFAULT_DOCKER_PATH}/traefik/config:/etc/traefik:ro #config-file = /etc/traefik/traefik.yml:ro
      # - ${DEFAULT_DOCKER_PATH}/traefik/log/access.log:/var/log/traefik/access.log
      # - ${DEFAULT_DOCKER_PATH}/traefik/log/traefik.log:/var/log/traefik/traefik.log
      - ${DEFAULT_DOCKER_PATH}/ssl/your.cert:/ssl/your.cert
      - ${DEFAULT_DOCKER_PATH}/ssl/key.cert:/ssl/your.key
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.providers.file.directory=/etc/traefik/dyn"
      - "traefik.providers.file.watch=true"
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DEFAULT_URL}`)"

  postgres:
    image: tensorchord/pgvecto-rs:pg16-v0.1.11
    container_name: postgres
    hostname: postgres.${DEFAULT_URL}
    restart: unless-stopped
    networks:
      proxy:
        ipv4_address: 172.20.255.3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - ${DEFAULT_DOCKER_PATH}/postgres:/var/lib/postgresql/data    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PW}

  authentik-worker:
    image: ghcr.io/goauthentik/server:latest
    container_name: authentik-worker
    hostname: authentik-worker.${DEFAULT_URL}
    restart: unless-stopped
    user: root
    networks:
      proxy:
        ipv4_address: 172.20.255.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - ${DEFAULT_DOCKER_PATH}/authentik/media:/media
      # - ${DEFAULT_DOCKER_PATH}/authentik/custom-templates:/templates
      # - ${DEFAULT_DOCKER_PATH}/geoip/data:/geoip
    environment:
      AUTHENTIK_POSTGRESQL__HOST: postgres.${DEFAULT_URL}
      AUTHENTIK_REDIS__HOST: redis.${DEFAULT_URL}
      AUTHENTIK_SECRET_KEY: 'some_secret_key'
      AUTHENTIK_POSTGRESQL__USER: postgres
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: ${POSTGRES_PW}
      AUTHENTIK_REDIS__DB: 9
      AUTHENTIK_ERROR_REPORTING__ENABLED: false
    command:
      - worker
    depends_on:
      - postgres
      - redis

  authentik-server:
    image: ghcr.io/goauthentik/server:latest
    container_name: authentik-server
    hostname: authentik-server.${DEFAULT_URL}
    restart: unless-stopped
    networks:
      proxy:
        ipv4_address: 172.20.255.5
    # volumes:
      # - ${DEFAULT_DOCKER_PATH}/authentik/media:/media
      # - ${DEFAULT_DOCKER_PATH}/authentik/custom-templates:/templates
    environment:
      AUTHENTIK_POSTGRESQL__HOST: postgres.${DEFAULT_URL}
      AUTHENTIK_REDIS__HOST: redis.${DEFAULT_URL}
      AUTHENTIK_SECRET_KEY: '${SECRET_KEY_FOR_AUTHENTIK}'
      AUTHENTIK_POSTGRESQL__USER: postgres
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: ${POSTGRES_PW}
      AUTHENTIK_REDIS__DB: 9
      AUTHENTIK_ERROR_REPORTING__ENABLED: false
    labels:
      - "traefik.enable=true"
      
      - "traefik.http.routers.authentik.rule=Host(`auth.${DEFAULT_URL}`)" 
      - "traefik.http.routers.authentik.entrypoints=websecure"
      - "traefik.http.routers.authentik.tls=true"
      - "traefik.http.routers.authentik.service=authentik-svc"
      
      ## Individual Application forwardAuth regex (catch any subdomain using individual application forwardAuth) 
      - "traefik.http.routers.authentik-outpost.rule=HostRegexp(`{subdomain:[a-z0-9-]+}.${DEFAULT_URL}`) && PathPrefix(`/outpost.goauthentik.io/`)"
      - "traefik.http.routers.authentik-outpost.entrypoints=websecure"
      - "traefik.http.routers.authentik-outpost.tls=true"      
      
      - "traefik.http.services.authentik-svc.loadBalancer.server.port=9000"
    command: server
    depends_on:
      - postgres
      - redis

  redis:
    image: docker.io/library/redis:alpine
    container_name: redis
    hostname: redis.${DEFAULT_URL}
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    networks:
      proxy:
        ipv4_address: 172.20.255.6
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
      
  yade:
    image: esperotech/yaade:latest
    container_name: yade
    hostname: yade.${DEFAULT_URL}
    restart: unless-stopped
    networks:
      proxy:
        ipv4_address: 172.20.255.7
    extra_hosts:
      auth.${DEFAULT_URL}: 172.20.255.2
    ports:
      - 9339:9339
    volumes:
      - ${DEFAULT_DOCKER_PATH}/yaade/data:/app/data    
    environment:
      YAADE_ADMIN_USERNAME: admin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.yaade.rule=Host(`yaade.${DEFAULT_URL}`)"
      - "traefik.http.routers.yaade.entrypoints=websecure"
      - "traefik.http.routers.yaade.tls=true"
      - "traefik.http.routers.yaade.tls.certresolver=dns"
      - "traefik.http.services.yaade.loadbalancer.server.port=9339"
      - "traefik.http.services.yaade.loadbalancer.server.scheme=http"

networks:
  proxy:
    external: true
```

When everything is set up, you need to create an application and provider in Authentication and modify the following OCID config for yaade:
```
{
    "providers": [{
        "id": "authentik",
        "label": "Login with Authentik",
        "provider": "oidc-discovery",
        "params": {
            "site": "https://auth.${DEFAULT_URL}/application/o/yaade/",
            "clientId": "clientid_from_authentik",
            "clientSecret": "clientsecret_from_authentik",
            "callbackUrl": "https://yaade..${DEFAULT_URL}/callback-yaade",
            "fields": {
                "username": "/sub",
                "groups": "/groups"
            },
            "scopes": ["openid", "email"]
        }
    }]
}
```


Since this is a shortened version and I unfortunately wasn't able to test it myself, I hope everything works as expected. I am sorry that this is still a lot of things to go through. But of course, if you encounter any problems, please do not hesitate to ask! Thanks again for your help!
